aprepasaurus/tudor/urls.py
# urls.py for tudor

from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'tudor'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^toot(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^seek(?P<pk>[0-9]+)/$', views.DetailSeekView.as_view(), name='detail_seek'),
    url(r'^tutor_upload$', views.tutor_upload, name='tutor_upload'),
    url(r'^seek_upload$', views.seek_upload, name='seek_upload'),
] 

aprepasaurus/tudor/models.py
#
# Models.py
#
# The main goal here is to make our models of Tutor, Review, and Prespective 
# Development focused on making the Tutor first and then slowly building how
# the tutor wanted to present themselves. 
#
# Author: jsp264
# Updated: 12/3/2017


# Create your models here.

import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Tutor(models.Model):
    screen_name         = models.CharField(max_length=100)
    teaching_start_date = models.DateTimeField('start date')
    teacher_email       = models.EmailField(max_length=200)
    teacher_address     = models.CharField(max_length=100)
    tutor_photo         = models.ImageField(upload_to = 'teachers/%Y/%m')
    alma_mater          = models.CharField(max_length=100)
    degree              = models.CharField(max_length=100)
    major               = models.CharField(max_length=50)
    years_xp            = models.PositiveIntegerField()

    def __str__(self):
        return self.screen_name

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.teaching_start_date <= now

class Seeker(models.Model):
    seek_name         = models.CharField(max_length=100)
    join_date         = models.DateTimeField('join_date')
    seekemail         = models.EmailField(max_length=200)
    is_parent         = models.BooleanField()
    seek_addr         = models.CharField(max_length=200)
    desired_subjects  = models.CharField(max_length=250)
    seek_photo        = models.ImageField(upload_to = 'seekers/%Y/%m')

    def __str__(self):
        return self.seek_name


class Specialty(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    spec_text = models.CharField(max_length=200)
    desc_text = models.CharField(max_length=500)

    def __str__(self):
        return self.spec_text

aprepasaurus/tudor/forms.py
# Image Upload File

# -*- coding: utf-8 -*-
from django import forms

class PhotoUploadForm(forms.Form):
    docfile = forms.ImageField(
        label='Select a photo of yourself!',
        help_text='max. 4 megabytes'
    )

SUBJECT_CHOICES = (
    ('sat_reading'  , '         SAT Reading         '),
    ('sat_writing'  , '         SAT Writing         '),
    ('sat_math'     , '       SAT Mathematics       '),
    ('sat_essay'    , '      SAT Essay Writing      '),
    ('toefl_speak'  , '        TOEFL Speaking       '),
    ('toefl_read'   , '        TOEFL Reading        '),
    ('toefl_writing', '        TOEFL Writing        '),
    ('toefl_listen' , '       TOEFL Listening       '),
    ('ap_world'     , '       AP World History      '),
    ('ap_euro'      , '     AP European History     '),
    ('ap_chem'      , '         AP Chemistry        '),
    ('ap_phys'      , '          AP Physics         '),
    ('ap_calc'      , '        AP Calculus BC       '),
    ('ap_lang'      , ' AP Language & Comp '),
    ('ap_lit'       , 'AP Literature & Comp'),
)

class SubjectsForm(forms.Form):
    subjects = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=SUBJECT_CHOICES,
    )

DEGREEES = (
	('Bachelors'  , 'Bachelors'),
	('Masters'    , 'Masters'),
	('Doctorate'  ,  'PhD'),
)

class DegreeForm(forms.Form):
	degrees = forms.ChoiceField(
		choices=DEGREEES,
		widget =forms.RadioSelect(),
	)

PARENT_CHOI = (
    ('Parent', 'Parent'),
    ('Student', 'Student'),
    )

class ParentForm(forms.Form):
    parentf = forms.ChoiceField(
        choices = PARENT_CHOI,
        widget=forms.RadioSelect(),
    )

aprepasaurus/tudor/views.py
#
# The Views module. Constructed to properly show the representations of our models appropriately
#
# Author: jsp264
# Date Modified: 12/3/2017


# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from .models import Tutor, Specialty, Seeker
from .forms import PhotoUploadForm, SubjectsForm, DegreeForm, ParentForm

import requests
import time

class IndexView(generic.ListView):
    template_name = 'tudor/index.html'
    context_object_name = 'available_tutors_list'

    def get_queryset(self):
        """
        Return the last five (changed to all) published questions (not including those set to be
        published in the future).
        """
        return Tutor.objects.filter(
            teaching_start_date__lte=timezone.now()
        ).order_by('-teaching_start_date')[:]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['seekers'] = Seeker.objects.all().order_by('join_date')[:]
        return context

class DetailView(generic.DetailView):
    model = Tutor
    template_name = 'tudor/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Tutor.objects.filter(teaching_start_date__lte=timezone.now())

class DetailSeekView(generic.DetailView):
    model = Seeker
    template_name = 'tudor/detail_seek.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Seeker.objects.filter(join_date__lte=timezone.now())

#################################################################################
############################ VIEW METHODS #######################################
#################################################################################

# tutor_upload logic may want to actually be in the model, not the view
def seek_upload(request):
    if request.method == 'POST':
        form  = PhotoUploadForm(request.POST, request.FILES)
        form2 = SubjectsForm(request.POST, request.FILES)
        form3 = ParentForm(request.POST, request.FILES)
        if form.is_valid():
            newseek = Seeker(seek_name          = request.POST['name'],
                             join_date          = timezone.now(),
                             seekemail          = request.POST['tootemail'],
                             seek_photo         = request.FILES['docfile'],
                             is_parent          = True if request.POST['degree'] == 'Parent' else False,
                             seek_addr          = request.POST['address'],
                             desired_subjects   = ' '.join(request.POST.getlist('subjects')) if request.POST.getlist('subjects') else "NONE"
            )

            newseek.save()

            return HttpResponseRedirect(reverse('tudor:index'))
    else:
        form = PhotoUploadForm() # A empty, unbound form
        form2 = SubjectsForm()   # A empty, unbound form
        form3 = ParentForm()

    seeks = Seeker.objects.all()
    return render(request,
                  'tudor/seek_upload.html',
                  {'seekers': seeks, 'form': form, 'form2': form2, 'form3': form3}
    )



def tutor_upload(request):
    # Handle file upload
    if request.method == 'POST':
        #tzone = "https://maps.googleapis.com/maps/api/timezone/json?location=38.908133,-77.047119&timestamp=1458000000&key=AIzaSyDgYrnLvtV8en5ARq-MxhNM_vTsyMUf0QA"
        #taddr = "https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=AIzaSyDIFo17NRLWr045Cl5UknH28ssW13pHsmI"
        form  = PhotoUploadForm(request.POST, request.FILES)
        form2 = SubjectsForm(request.POST, request.FILES)
        form3 = DegreeForm(request.POST, request.FILES)
        if form.is_valid():

            # clean address
            # TODO

            addr_info = requests.get("https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=AIzaSyDIFo17NRLWr045Cl5UknH28ssW13pHsmI")
            addr_info_dict = addr_info.json()
            cur_timestamp = str(int(time.time()))

            latlng = (str(addr_info_dict['results'][0]['geometry']['location']['lat']),str(addr_info_dict['results'][0]['geometry']['location']['lng']))

            api_key  = "AIzaSyDgYrnLvtV8en5ARq-MxhNM_vTsyMUf0QA"
            tzonepre = "https://maps.googleapis.com/maps/api/timezone/json?location="
            tzone_info = requests.get(tzonepre+latlng[0]+','+latlng[1]+'&timestamp='+cur_timestamp+'&key='+api_key).json()


            newteach = Tutor(screen_name         = request.POST['name'], 
                             teaching_start_date = timezone.now(),
                             teacher_email       = tzone_info['timeZoneName'], #request.POST['tootemail'],
                             teacher_address     = request.POST['address'],
                             tutor_photo         = request.FILES['docfile'],
                             alma_mater          = request.POST['college'],
                             degree              = request.POST['degree'],
                             major               = request.POST['major'],
                             years_xp            = 2)

            newteach.save()
            mysubs = '- - -'.join(request.POST.getlist('subjects')) if request.POST.getlist('subjects') else "NONE"
            newteach.specialty_set.create(spec_text='SPECIALTIES',
                                          desc_text=mysubs)
            newteach.save()


            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('tudor:index'))
    else:
        form = PhotoUploadForm() # A empty, unbound form
        form2 = SubjectsForm()   # A empty, unbound form
        form3 = DegreeForm()


    # Load documents for the list page
    teachers = Tutor.objects.all()

    # Render list page with the documents and the form
    return render(request,
        'tudor/tutor_upload.html',
        {'teachers': teachers, 'form': form, 'form2': form2, 'form3': form3}
    )

#class ResultsView(generic.DetailView):
#    model = Question
#    template_name = 'polls/results.html'
#
#def vote(request, question_id):
#   question = get_object_or_404(Question, pk=question_id)
#    try:
#        selected_choice = question.choice_set.get(pk=request.POST['choice'])
#    except (KeyError, Choice.DoesNotExist):
#        # Redisplay the question voting form.
#        return render(request, 'polls/detail.html', {
#            'question': question,
#            'error_message': "You didn't select a choice.",
#        })
#    else:
#        selected_choice.votes += 1
#        selected_choice.save()
#        # Always return an HttpResponseRedirect after successfully dealing
#        # with POST data. This prevents data from being posted twice if a
#        # user hits the Back button.
#        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

aprepasaurus/tudor/templates/tudor/detail.html
<!-- DETAIL -->

<html>
<head>
	<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e6c5625f34c996152221a935657627be&libraries=services"></script>
	<meta charset="utf-8"/>
	<title>Tutor Page</title>
</head>
{% load static %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% include "tudor/header.html" %}

<link rel="stylesheet" type="text/css" href="{% static 'tudor/styles.css' %}" />

<div class='row' id="king-div">
<div class="col-sm-4" id='toot-detail-div'>
<h1 id='toot-name'>{{ tutor.screen_name }}</h1>
<h2>{{tutor.teacher_email}}<h2>

<img src="../../media/{{ tutor.tutor_photo.name }}" alt="TUTOR_PHOTO" height="200" width="200" vspace="20">

<div class="college-text"><h3>{{tutor.alma_mater}}</h3>
<h4>{{tutor.degree}} of {{tutor.major}}</h4></div> <br><br>

<h3 id='toot-name'>Preferred Meeting Place</h3>

<div id="map" style="width:350px;height:250px;" hspace="20"></div>
	<script>
		var container = document.getElementById('map');
		var options = {
			center: new daum.maps.LatLng(33.450701, 126.570667),
			level: 4
		};
		var map = new daum.maps.Map(container, options);

		window.onload = function(){

		var geocoder = new daum.maps.services.Geocoder();

		// 주소로 좌표를 검색합니다
		var address = "";
		if ("{{tutor.teacher_address}}" == '') {
			address='서울특별시 강남구 논현로 167길 19, 남도빌딩'
		}
		else{
			address = "{{tutor.teacher_address}}";
		}
		geocoder.addressSearch(address, function(result, status) {

    	// 정상적으로 검색이 완료됐으면 
     	if (status === daum.maps.services.Status.OK) {

        var coords = new daum.maps.LatLng(result[0].y, result[0].x);

        // 결과값으로 받은 위치를 마커로 표시합니다
        var marker = new daum.maps.Marker({
            map: map,
            position: coords
        });

        // 인포윈도우로 장소에 대한 설명을 표시합니다
        if (address=='서울특별시 강남구 논현로 167길 19, 남도빌딩') address = '앤디프랩';
        var infowindow = new daum.maps.InfoWindow({
            content: '<div style="width:150px;text-align:center;padding:6px 0;">' + address + '</div>'
        });
        infowindow.open(map, marker);

        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
    	} 
		});    
	}
	</script><br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h3 id='toot-name'>Available Subjects</h3>

{% csrf_token %}
{% for spec in tutor.specialty_set.all %}
    <name="spec" id="choice{{ forloop.counter }}" value="{{ spec.id }}" />
    <label for="choice{{ forloop.counter }}"><h4>{{ spec.spec_text }}</h4></label><br />
    <p>{{spec.desc_text}}</p><br/>
{% endfor %}
</div>
</div>

</html>

aprepasaurus/tudor/templates/tudor/detail_seek.html
<!-- DETAIL FOR CUSTOMER   maps_api_key: AIzaSyDgYrnLvtV8en5ARq-MxhNM_vTsyMUf0QA  -->

<html>
<head>
	<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e6c5625f34c996152221a935657627be&libraries=services"></script>
	<meta charset="utf-8"/>
	<title>Customer Page</title>
</head>
{% load static %}

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% include "tudor/header.html" %}

<link rel="stylesheet" type="text/css" href="{% static 'tudor/styles.css' %}" />

<div class='row' id="king-div-seek-1">
<div class="col-sm-4" id='toot-detail-div'>
<h1 id='toot-name'>{{ seeker.seek_name }}</h1>
<h2>{{seeker.seekemail}}<h2>

<img src="../../media/{{ seeker.seek_photo.name }}" alt="PERSON_PHOTO" height="200" width="200" vspace="20">

<h3 id='toot-name'>Preferred Meeting Place</h3>

<div id="map" style="width:350px;height:250px;" hspace="20"></div>
	<script>
		var container = document.getElementById('map');
		var options = {
			center: new daum.maps.LatLng(33.450701, 126.570667),
			level: 4
		};
		var map = new daum.maps.Map(container, options);

		window.onload = function(){

		var geocoder = new daum.maps.services.Geocoder();

		// 주소로 좌표를 검색합니다
		var address = "";
		if ("{{seeker.seek_addr}}" == '') {
			address='서울특별시 강남구 논현로 167길 19, 남도빌딩'
		}
		else{
			address = "{{seeker.seek_addr}}";
		}
		geocoder.addressSearch(address, function(result, status) {

    	// 정상적으로 검색이 완료됐으면 
     	if (status === daum.maps.services.Status.OK) {

        var coords = new daum.maps.LatLng(result[0].y, result[0].x);

        // 결과값으로 받은 위치를 마커로 표시합니다
        var marker = new daum.maps.Marker({
            map: map,
            position: coords
        });

        // 인포윈도우로 장소에 대한 설명을 표시합니다
        if (address=='서울특별시 강남구 논현로 167길 19, 남도빌딩') address = '앤디프랩';
        var infowindow = new daum.maps.InfoWindow({
            content: '<div style="width:150px;text-align:center;padding:6px 0;">' + address + '</div>'
        });
        infowindow.open(map, marker);

        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
    	} 
		});    
	}
	</script><br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h3 id='toot-name'>Desired Subjects</h3>
<p>{{seeker.desired_subjects}}</p>

<!--
{% csrf_token %}
{% for spec in tutor.specialty_set.all %}
    <name="spec" id="choice{{ forloop.counter }}" value="{{ spec.id }}" />
    <label for="choice{{ forloop.counter }}"><h4>{{ spec.spec_text }}</h4></label><br />
    <p>{{spec.desc_text}}</p><br/>
{% endfor %}-->
</div>
</div>

</html>

aprepasaurus/tudor/templates/tudor/header.html
<!DOCTYPE html>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tudor/styles.css' %}" />
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">


<html>
    <head>
        <meta charset="utf-8">
        <title>APREPASAURUS</title>   
    </head>

<header class = "navbar navbar-default" role = "banner">
<div class = "container">
    <div class ="navbar-header">
        <button type = "button" class= "navbar-toggle" data-toggle = "collapse" data-target = "#dropdown">
            <span class = "sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <p><a href="{% url 'tudor:index' %}" class ="navbar-brand">ANDY PREP: 앤디프랩,어학원,NEW SAT,ACT,iBT TOEFL,SSAT</a></p>
    </div><!-- End Navbar Header-->

    <div class = "collapse navbar-collapse" id = "dropdown">

        <ul class = "nav navbar-nav navbar-right" role = "navigation">
            <li><a href="#" class='ghor'>Not Sure</a></li>
            <li><a href="{% url 'tudor:tutor_upload' %}">New Tutor Page</a></li>
            <li><a href="{% url 'tudor:seek_upload' %}">New Customer Page</a></li>
            <li><a href="#">Tutor Search</a></li>
        </ul>      

    </div><!-- End Nav Contents -->
</div><!-- End Container -->
</header>



</html>

aprepasaurus/tudor/templates/tudor/index.html
<!--new index woo!-->

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tudor/styles.css' %}" />
{% include "tudor/header.html" %}

<h4> TUTORS </h4>

{% if available_tutors_list %}
    <ul>
    {% for tutor in available_tutors_list  %}
        <li><a href="{% url 'tudor:detail' tutor.id %}">{{ tutor.screen_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no Tutors available at the moment :(</p>
{% endif %}

<h4> CUSTOMERS </h4>

{% if seekers %}
    <ul>
    {% for seek in seekers  %}
        <li><a href="{% url 'tudor:detail_seek' seek.id %}">{{ seek.seek_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no Customers available at the moment :(</p>
{% endif %}

aprepasaurus/tudor/templates/tudor/results.html
<!-- results.html -->

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

aprepasaurus/tudor/templates/tudor/seek_upload.html
<!DOCTYPE html>

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% include "tudor/header.html" %}
<html>
    <head>
        <meta charset="utf-8">
        <title>TUTOR UPLOAD PAGE!</title>   
    </head>
    <body>

        <!-- Upload form. Note enctype attribute! -->
        <div class='row' id="king-div-see">
        <div class='col-sm-4' id='toot-detail-div-cor'>
        <h2 id="toot-name">NEW CUSTOMER</h2>
        <form action="{% url 'tudor:seek_upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
            <p id='see-pub'>   {{ form.docfile }}</p>
            </p><br><br><br>
            <h2 id="toot-name"> PROFILE QUESTIONS </h2>
            <h5> 1. What is your Name? </h5>
            <p><input type="text"   class="form-control"  name="name" placeholder="이름이 뭐예요?" required/></p><br>
            <h5> 2. What is your Email? </h5>
            <p><input type="email"   class="form-control"  name="tootemail" placeholder="이메일 주소가 어떻게 되세요?" required/></p><br>
            <h5> 3. Do you have a preferred address? (please enter in Korean) </h5>
            <p><input type="text"   class="form-control"  name="address" placeholder="선호하는 주소가 있나요? AndyPrep에 대해 비워 둠 (한국어를 입력해 주세요)" /></p><br>
            <h5> 5. Are you a student or a parent? </h5>
            
            <div class="btn-group"> 
            {% for dgree in form3.parentf %}
                <label class="btn btn-success">
                <input type="radio" name="degree" value="{{dgree.choice_label}}" id="id_subjects_{{forloop.counter}}" /> {{ dgree.choice_label }}
                </label>
            {% endfor %}
            </div><br><br><br>

            <h5> 7. What Subjects are you interested in? </h5>
            <div class="btn-group"> 
            {% for checkbox in form2.subjects %}
                <label class="btn btn-info" id="sub-css">
                <input type="checkbox" name="subjects" value="{{checkbox.choice_label}}" id="id_subjects_{{forloop.counter}}" /> {{ checkbox.choice_label }}
                </label><br>
            {% endfor %}
            </div>
            <br>

            <p><input type="submit" id="tu-submit" class="btn btn-warning active" value="Submit Your Profile!"/></p><br>
        </form>
        </div>
        </div>
    </body>
</html> 

aprepasaurus/tudor/templates/tudor/tutor_upload.html
<!DOCTYPE html>

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% include "tudor/header.html" %}
<html>
    <head>
        <meta charset="utf-8">
        <title>TUTOR UPLOAD PAGE!</title>   
    </head>
    <body>

        <!-- Upload form. Note enctype attribute! -->
        <div class='row' id="upload-main-div">
        <div class='col-sm-4' id='toot-detail-div-cor-1'>
        <h2 id="toot-name"> NEW TUTOR </h2>
        <form action="{% url 'tudor:tutor_upload' %}" method="post" enctype="multipart/form-data" id="tuform">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p><br><br><br>
            <h2 id="toot-name"> PROFILE QUESTIONS </h2>
            <h5> 1. What is your Name? </h5>
            <p><input type="text"   class="form-control"  name="name" placeholder="이름이 뭐예요?" required/></p><br>
            <h5> 2. What is your Email? </h5>
            <p><input type="email"   class="form-control"  name="tootemail" placeholder="이메일 주소가 어떻게 되세요?" required/></p><br>
            <h5> 3. Do you have a preferred address? (please enter in Korean)</h5>
            <p><input type="text"   class="form-control"  name="address" placeholder="선호하는 주소가 있나요? AndyPrep에 대해 비워 둠 (한국어를 입력해 주세요)" /></p><br>
            <h5> 4. Where did you Attend College? </h5> 
            <p><input type="text"   class="form-control"  name="college" placeholder="너는 대학에 다닌 적이 있니?" /></p><br>
            <h5> 5. What type of Degree did you receive from there? </h5>
            
            <div class="btn-group"> 
            {% for dgree in form3.degrees %}
                <label class="btn btn-success">
                <input type="radio" name="degree" value="{{dgree.choice_label}}" id="id_subjects_{{forloop.counter}}" /> {{ dgree.choice_label }}
                </label>
            {% endfor %}</div><br><br><br>

            <h5> 6. What was your field of study for that Degree? </h5> 
            <p><input type="text" class="form-control"  name="major" placeholder="뭐 전공했어요?" /></p><br>
            <h5> 7. What Subjects are you able to Teach? </h5>
            <div class="btn-group"> 
            {% for checkbox in form2.subjects %}
                <label class="btn btn-info" id="sub-css">
                <input type="checkbox" name="subjects" value="{{checkbox.choice_label}}" id="id_subjects_{{forloop.counter}}" /> {{ checkbox.choice_label }}
                </label><br>
            {% endfor %}
            </div>
            <br>

            <p><input type="submit" id="tu-submit" class="btn btn-warning active" value="Submit Your Profile!"/></p><br>
        </form>
        </div>
        </div>
    </body>
</html> 